### ISSUE TITLE
Multithread apps can create multiple threads tp update expired value

### ISSUE THREAD

**Issue by NShahri** [cliechty/AsyncCache#2]
It seems when we use AsyncCache in multithread apps, there is a possibility to create multiple thread to update the expired value.

If two or more threads try to get the value (expired value) of a key in the same time, AsyncCache creates new updating threads for each request. I expect to create only one thread.

Bug fix: https://github.com/cliechty/AsyncCache/pull/1

**Comment by cliechty** [comment]
Thanks for finding that issue. I had no idea anyone was using this library. FYI I had to modify the test you added so that it would pass if all the tests were run at once. It needed an isolated cache key.
